# Generated by Django 6.0.2 on 2026-02-16 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_web_playable',
            field=models.BooleanField(default=False, verbose_name='Jugable en web'),
        ),
        migrations.AddField(
            model_name='game',
            name='processing_error',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Error de procesamiento'),
        ),
        migrations.AddField(
            model_name='game',
            name='web_build_path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Ruta web del build'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_file',
            field=models.FileField(blank=True, help_text='Archivo ZIP web con index.html (max 500MB)', null=True, upload_to='games/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])], verbose_name='Archivo del juego'),
        ),
    ]
