# Generated by Django 6.0.3 on 2026-03-06 14:33

import apps.web.storage_backends
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_gamerating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover_image',
            field=models.ImageField(storage=apps.web.storage_backends.GameCoversStorage(), upload_to='', verbose_name='Imagen de portada'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_file',
            field=models.FileField(blank=True, help_text='Archivo ZIP web con index.html (max 500MB)', null=True, storage=apps.web.storage_backends.GameFilesStorage(), upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])], verbose_name='Archivo del juego'),
        ),
    ]
