# Generated by Django 6.0.2 on 2026-03-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_gamerating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover_image',
            field=models.URLField(blank=True, default='', help_text='URL pública de la portada en Supabase Storage', verbose_name='Imagen de portada'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_file',
            field=models.URLField(blank=True, default='', help_text='URL pública del ZIP en Supabase Storage', verbose_name='Archivo del juego (URL)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='web_build_path',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='URL del build web'),
        ),
    ]
