# Generated by Django 6.0.2 on 2026-03-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_game_cover_image_alter_game_game_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_processing',
            field=models.BooleanField(default=False, help_text='True mientras el ZIP se está extrayendo en segundo plano.', verbose_name='En procesamiento'),
        ),
    ]
