# Generated by Django 6.0.2 on 2026-03-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_game_is_processing'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_rejected',
            field=models.BooleanField(default=False, help_text='True si el juego fue rechazado por un moderador', verbose_name='Rechazado'),
        ),
        migrations.AddField(
            model_name='game',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de rechazo'),
        ),
    ]
