import mimetypes
from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand
from django.core.files.storage import default_storage

from apps.web.storage_backends import AvatarStorage


class Command(BaseCommand):
    help = 'Sube los avatares predeterminados de static/avatars/ a Supabase Storage (default_avatars/)'

    def handle(self, *args, **options):
        avatars_dir = Path(settings.BASE_DIR) / 'static' / 'avatars'
        
        if not avatars_dir.exists():
            self.stdout.write(self.style.ERROR(f'El directorio {avatars_dir} no existe.'))
            return
            
        storage = AvatarStorage()
        
        # We want to put them in a folder called 'default_avatars' or just upload them and we track their names.
        # AvatarStorage puts things in 'avatars/'. Let's reuse that or create a specific path for defaults
        # To make it simple, we upload them as 'default_avatars/filename.ext' but since AvatarStorage
        # forces the 'avatars/' prefix, they will end up as 'avatars/default_avatars/filename.ext'. 
        # Actually AvatarStorage does not force it if we just pass a name, but wait, in S3Boto3Storage
        # the path is `location + name`. The Location on AvatarStorage is 'avatars'. So it will be avatars/filename
        # That's perfectly fine. We can just upload them directly to `avatars/` just like user avatars.
        # But wait, user avatars receive a random name generated by Django when user uploads (actually user profile has it as 'avatar').
        # Using simply avatars/sonriente.png is fine.
        
        count = 0
        for avatar_file in avatars_dir.iterdir():
            if avatar_file.is_file() and avatar_file.suffix.lower() in ['.png', '.jpg', '.jpeg']:
                file_name = avatar_file.name
                
                # Check if file already exists in remote storage to prevent duplicates
                if storage.exists(file_name):
                    self.stdout.write(self.style.WARNING(f'El avatar {file_name} ya existe en Supabase. Omitiendo.'))
                    continue
                
                content_type, _ = mimetypes.guess_type(str(avatar_file))
                if not content_type:
                    content_type = 'image/png'
                    
                with avatar_file.open('rb') as f:
                    # Upload to storage
                    self.stdout.write(f'Subiendo {file_name}...')
                    saved_path = storage.save(file_name, f)
                    
                    self.stdout.write(self.style.SUCCESS(f'OK: {saved_path}'))
                    count += 1
                    
        self.stdout.write(self.style.SUCCESS(f'\nProceso completado. Se subieron {count} avatares por defecto.'))
