# Generated by Django 6.0.2 on 2026-02-16 12:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('short_description', models.CharField(help_text='Breve resumen del juego', max_length=300, verbose_name='Descripción corta')),
                ('cover_image', models.ImageField(upload_to='games/covers/', verbose_name='Imagen de portada')),
                ('genre', models.CharField(choices=[('accion', 'Acción'), ('aventura', 'Aventura'), ('estrategia', 'Estrategia'), ('rpg', 'RPG'), ('deportes', 'Deportes'), ('carreras', 'Carreras'), ('puzzle', 'Puzzle'), ('simulacion', 'Simulación'), ('terror', 'Terror'), ('multijugador', 'Multijugador'), ('otro', 'Otro')], max_length=100, verbose_name='Género')),
                ('game_file', models.FileField(blank=True, help_text='Archivo comprimido (.zip, .rar, .7z) - Máx 500MB', null=True, upload_to='games/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar', '7z'])], verbose_name='Archivo del juego')),
                ('external_url', models.URLField(blank=True, help_text='Link para jugar online (opcional)', verbose_name='URL externa')),
                ('downloads', models.IntegerField(default=0, verbose_name='Descargas')),
                ('views', models.IntegerField(default=0, verbose_name='Vistas')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Calificación')),
                ('is_approved', models.BooleanField(default=False, help_text='Solo juegos aprobados son visibles públicamente', verbose_name='Aprobado')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Juego',
                'verbose_name_plural': 'Juegos',
                'ordering': ['-created_at'],
            },
        ),
    ]
