# Generated by Django 6.0.2 on 2026-02-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_game_is_web_playable_game_processing_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rating_votes',
            field=models.PositiveIntegerField(default=0, verbose_name='Total de votos'),
        ),
    ]
