# Generated by Django 6.0.2 on 2026-03-01 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
