# Generated by Django 6.0.2 on 2026-03-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_friendrequest_idx_friend_request_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Foto de perfil', null=True, upload_to='avatars/'),
        ),
    ]
