# Generated by Django 6.0.3 on 2026-03-10 14:11

import apps.web.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_avatar_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Foto de perfil', null=True, storage=apps.web.storage_backends.AvatarStorage(), upload_to=''),
        ),
    ]
